artifacts_root: artifacts

data_ingestion:
   root_dir       : artifacts/data_ingestion
   source_URL     : https://github.com/vivek-yogi/Repo/raw/main/books.zip
   local_data_file: artifacts/data_ingestion/books.zip
   unzip_dir      : artifacts/data_ingestion

DataLoadingConfig:
  books_csv_file    : BX-Books.csv
  ratings_csv_file  : BX-Book-Ratings.csv
  users_csv_file    : BX-Users.csv
  