artifacts_root: artifacts

data_ingestion:
   root_dir       : artifacts/data_ingestion
   source_URL     : https://github.com/vivek-yogi/Repo/raw/main/books.zip
   local_data_file: artifacts/data_ingestion/books.zip
   unzip_dir      : artifacts/data_ingestion
